from typing import List, Dict
from datetime import datetime

class ReportGenerator:
    """
    Report Generator Agent that creates comprehensive research reports.
    """
    
    def __init__(self):
        self.report_template = """
# Research Report: {topic}

**Generated:** {timestamp}

---

## Executive Summary

{summary}

---

## Key Findings

{key_findings}

---

## Detailed Analysis

{detailed_analysis}

---

## Sources and References

{sources}

---

## Conclusion

{conclusion}

---

*Report generated by AI Research Assistant*
"""
    
    def generate(self, topic: str, search_results: List[Dict], 
                 summary: str, include_citations: bool = True) -> str:
        """
        Generate a comprehensive research report.
        
        Args:
            topic: Research topic
            search_results: List of search results
            summary: Executive summary
            include_citations: Whether to include source citations
            
        Returns:
            Formatted research report in Markdown
        """
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Generate key findings
        key_findings = self._generate_key_findings(search_results)
        
        # Generate detailed analysis
        detailed_analysis = self._generate_detailed_analysis(topic, search_results)
        
        # Generate sources section
        sources = self._generate_sources_section(search_results, include_citations)
        
        # Generate conclusion
        conclusion = self._generate_conclusion(topic, search_results)
        
        # Fill template
        report = self.report_template.format(
            topic=topic,
            timestamp=timestamp,
            summary=summary,
            key_findings=key_findings,
            detailed_analysis=detailed_analysis,
            sources=sources,
            conclusion=conclusion
        )
        
        return report
    
    def _generate_key_findings(self, search_results: List[Dict]) -> str:
        """Generate key findings section"""
        findings = []
        
        for idx, result in enumerate(search_results[:5], 1):
            title = result.get('title', 'N/A')
            snippet = result.get('snippet', 'No information available')
            
            # Create a key finding from the snippet
            finding = f"**{idx}. {title}**\n\n{snippet}"
            findings.append(finding)
        
        if not findings:
            return "No significant findings available from the search results."
        
        return "\n\n".join(findings)
    
    def _generate_detailed_analysis(self, topic: str, search_results: List[Dict]) -> str:
        """Generate detailed analysis section"""
        
        if not search_results:
            return f"Limited information available for detailed analysis on {topic}."
        
        analysis_parts = []
        
        # Introduction
        analysis_parts.append(f"### Overview\n\nThis analysis examines {topic} based on information gathered from {len(search_results)} sources.")
        
        # Main content from sources
        analysis_parts.append("\n### Information from Sources\n")
        
        for idx, result in enumerate(search_results, 1):
            source_name = result.get('source', 'Unknown')
            snippet = result.get('snippet', 'No information available')
            
            analysis_parts.append(f"**Source {idx} ({source_name}):**\n\n{snippet}\n")
        
        # Synthesis
        analysis_parts.append("\n### Synthesis\n")
        analysis_parts.append(f"Based on the gathered information, {topic} is a subject of significant interest with multiple perspectives and findings. ")
        analysis_parts.append("The sources provide various insights that contribute to a comprehensive understanding of this topic.")
        
        return "\n".join(analysis_parts)
    
    def _generate_sources_section(self, search_results: List[Dict], 
                                   include_citations: bool) -> str:
        """Generate sources and references section"""
        
        if not search_results:
            return "No sources available."
        
        sources = []
        
        for idx, result in enumerate(search_results, 1):
            title = result.get('title', 'Unknown Title')
            url = result.get('url', 'No URL')
            source = result.get('source', 'Unknown')
            
            if include_citations:
                # IEEE-style citation
                citation = f"[{idx}] \"{title},\" *{source}*. [Online]. Available: {url}"
                sources.append(citation)
            else:
                sources.append(f"{idx}. [{title}]({url})")
        
        return "\n\n".join(sources)
    
    def _generate_conclusion(self, topic: str, search_results: List[Dict]) -> str:
        """Generate conclusion section"""
        
        num_sources = len(search_results)
        
        conclusion = f"""
This research report on {topic} has compiled information from {num_sources} sources. 
The findings provide valuable insights into this subject matter. 

### Key Takeaways:

- Multiple sources confirm the relevance and importance of {topic}
- The information gathered represents diverse perspectives and data points
- Further research may be beneficial for deeper understanding

### Recommendations:

For those interested in exploring this topic further, we recommend:
- Reviewing the cited sources in detail
- Conducting follow-up research on specific aspects of interest
- Staying updated with new developments in this field

This report serves as a comprehensive starting point for understanding {topic} and can be used as a foundation for further investigation.
"""
        
        return conclusion.strip()
    
    def generate_quick_summary(self, topic: str, search_results: List[Dict]) -> str:
        """Generate a quick one-paragraph summary"""
        
        if not search_results:
            return f"No information found for {topic}."
        
        num_sources = len(search_results)
        first_snippet = search_results[0].get('snippet', 'No information available')
        
        summary = f"Research on '{topic}' reveals: {first_snippet} "
        summary += f"This finding is supported by {num_sources} sources that provide additional context and information on the subject."
        
        return summary
